name: Build SoftEther VPN

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libreadline-dev libssl-dev zlib1g-dev
    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools
      
    - name: Build SoftEther VPN
      run: |
        ./configure
        CC=musl-gcc make

    - name: List build directory
      run: ls -alh

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: softether-vpn
        path: |
          tmp/as/
          bin/
