name: Build SoftEther VPN

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: centos-7

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo yum update -y
        sudo yum groupinstall -y "Development Tools"
        sudo yum install -y readline-devel openssl-devel zlib-devel

    - name: Build SoftEther VPN
      run: |
        ./configure
        make

    - name: List build directory
      run: ls -alh

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: softether-vpn
        path: |
          tmp/as/
          bin/
